Model:
  in_channels: 12
  num_classes: 5
  model_type: 'YOLO'
  config_file: 'models/yolo_config.yaml'
  scale: 'n'

Loader:
  train_bs: 8
  val_bs: 8
  down: [2, 4, 8, 16, 32]

Optimizer:
  type: 'Adam'
  lr: 0.001

Losses:
  type: ['focal', 'dice']
  weight: True

Train:
  epochs: 1000
  device: 'cuda:1'
  focal_gain: 1
  dice_gain: 1
  ct_gain: 10

Test:
  model_weight: 'ckpt/v2/best.pth'
  device: 'cuda:0'
  threshold: 0.5
  min_area: 10000
  split_size: 512
  overlap: 256
  imgsz: 1024
